function msn = AEGAinputs()
%AEGAINPUTS  Single source of truth for AEGA design inputs.
%
%   msn = AEGAinputs()   returns the current baseline input struct.
%
%   Every script in the toolchain (AEGAweight, AEGAsize, AEGAconstraint,
%   blow_wind) reads from this struct and NEVER writes to it. Loop state
%   (DG, SW, PTO_kW, Ebat, Dprop) is passed separately, because those
%   are results, not choices.
%
%   To run a case, copy and override. Do NOT edit this file to try things:
%       msn = AEGAinputs();
%       msn.AR = 10;  msn.NPROP = 6;
%       out = AEGAsize(msn);
%
%   Values deliberately NOT here, because they belong to one script only:
%     AEGAweight   - FLOPS Table 1 constants A1..A7, CAYF, PCTL, FSTRT,
%                    FAERT, VARSWP
%     AEGAsize     - NMAX, TOL, secant update
%     AEGAconstraint - ROC target, climb/turn speeds, load factor, TOP
%
%   UNITS: weight lb | length ft | area ft^2 | speed ft/s unless the field
%          name says otherwise | density slug/ft^3 | power kW | energy kWh
%
%   OWNER: one person. Changes go through review, not straight to main.

%% ===================== MISSION REQUIREMENTS =========================
msn.payload  = 400;      % lb, 2 x (185 + 15)
msn.range    = 250;      % nautical miles. THE ASSIGNED REQUIREMENT IS 300.
                         %   250 is the team's negotiated position: 300 nm
                         %   costs +1090 lb and PPL solo cross-country is
                         %   150 nm. Set back to 300 to size the assigned
                         %   case; it is worth about 650 lb at MTOW.
msn.reserve  = 45;       % minutes at cruise
msn.Vkt      = 120;      % cruise, knots TRUE airspeed
msn.VS0      = 60;       % stall, knots CALIBRATED, landing config.
                         %   14 CFR Part 22 / MOSAIC limit is 61 KCAS.
                         %   NOT 45 kt: that is the pre-MOSAIC LSA rule.
msn.VS1_op   = 59;       % KCAS, CLEAN. Sport-pilot operation, 14 CFR 61.316.
                         %   Different test from VS0. Not currently enforced
                         %   anywhere in the toolchain - open question.
msn.ovh      = 0.04;     % taxi, takeoff, climb, descent energy allowance
msn.S_field  = 1500;     % ft, field length over a 50 ft obstacle. Used by
                         %   AEGAconstraint for BOTH takeoff and landing.
msn.enforce_VS1  = false; % true: size W/S to the VS1_op sport-pilot limit
msn.enforce_land = false; % true: size W/S to landing over 50 ft in S_field
msn.dV_ne    = 50;       % kt, never-exceed margin over cruise. Equivalent to
                         %   VD = 1.417 VC. Should be a formula tied to the
                         %   ASTM F2245 design speeds, not a constant.

%% ===================== TOOLCHAIN CONTROL ============================
msn.fpow      = 0.50;    % fraction of installed power held at the stall
                         %   condition in blow_wind. The certification test
                         %   is at IDLE power; even assuming the rule changes,
                         %   the case that matters is approach, not full
                         %   takeoff power. Do not set this to 1 and quote it.
msn.CLmax_cap = 4.0;     % hard cap on the blown CLmax. A STATED ASSUMPTION,
                         %   not a computed result. The dynamic-pressure
                         %   blend has no upper bound and knows nothing about
                         %   separation, so without this it runs away.

%% ===================== ATMOSPHERE ===================================
msn.h_cr     = 5000;             % ft, cruise altitude
msn.rho_SL   = 0.002377;         % slug/ft^3, sea level ISA
msn.rho_cr   = 0.002048;         % slug/ft^3, ISA at 5000 ft
msn.mu_cr    = 3.68041e-7;       % DYNAMIC viscosity, slug/(ft*s)
msn.nu_cr    = msn.mu_cr/msn.rho_cr;   % KINEMATIC viscosity, ft^2/s
msn.g0       = 32.174;           % ft/s^2

%% ===================== AERODYNAMIC COEFFICIENTS =====================
msn.CLmax_clean = 1.6;   % NO SOURCE. Drives the VS1 sport-pilot check.
msn.CLmax_TO    = 2.1;   % NO SOURCE. Input, not a flap calculation.
msn.CLmax_L     = 2.1;   % NO SOURCE. Landing config, IDLE POWER per
                         %   14 CFR 23.2110 / ASTM F2245. Blown-wing credit
                         %   is an assumed rule change, not current law.
msn.e_osw       = 0.80;  % Oswald factor. Constraint script previously used
                         %   0.70; they must agree.

%% ===================== WING =========================================
msn.AR     = 9;          % LOW for torsional stiffness with leading-edge
                         %   propulsors (whirl flutter). GJ scales roughly as
                         %   chord^4, so AR 8 is about 3x stiffer than AR 14.
                         %   COST: 258 lb at MTOW (2744 vs 2486) and 3.3
                         %   points of cruise L/D. The stiffness argument was
                         %   made when the wing was 79 ft^2 with a 25 ft span;
                         %   it is now ~107 ft^2 with 4.1 ft of chord, which
                         %   may already be stiffer than needed. YOUR CALL -
                         %   left at 8 deliberately, not overwritten.
msn.TR     = 0.45;       % FLOPS general aviation default, Table 1
msn.SWEEP  = 2;          % QUARTER-CHORD sweep, deg (FLOPS Eq. 14 wants c/4)
msn.TCA    = 0.15;       % NO SOURCE. Needs a named airfoil from aero.
msn.FCOMP  = 0.9;        % composite fraction, 0 metal to 1 all carbon
msn.FLAPR  = 0.333;      % movable surface area / wing area, FLOPS default

%% ===================== TAILS ========================================
msn.Vh     = 0.60;       % horizontal tail volume coefficient
msn.Vv     = 0.040;      % vertical tail volume coefficient
msn.Lh     = 12.47;      % ft, horizontal tail arm
msn.Lv     = 12.47;      % ft, vertical tail arm
msn.ARVT   = 1.5;        % vertical tail aspect ratio. Confirm with controls.
msn.TCVT   = 0.10;       % NO SOURCE. Implies a NACA 0010-class section.
msn.SWPVT  = 20;         % deg. NO SOURCE. Measure off the fin layout.
msn.HHT    = 1;          % 0 body-mounted tail, 1 T-tail (+20% fin weight).
                         %   T-tail balances the blown-wing pitching moment,
                         %   as on the Electra EL-2 Goldfinch.

%% ===================== FUSELAGE =====================================
msn.XL     = 22.0;       % ft, length. NO SOURCE - needs a station diagram.
msn.WFus   = 3.66;       % ft, max width. Side-by-side, at the anthropometric
                         %   minimum (~44 in external, ~40 in internal).
msn.DFus   = 4.16;       % ft, max depth. Reclined seating would give ~3.70
                         %   and is the largest remaining aero lever.
msn.XLP    = 4.0;        % ft, cabin length (drives furnishings)

%% ===================== DRAG BUILD-UP ================================
msn.SMISC  = 48.4;       % ft^2, gear fairings, canopy, junctions. NO SOURCE.
msn.SCOV   = 6.78;       % ft^2, wing area buried in the fuselage
msn.WETR   = 2.05;       % wetted / planform ratio, wing and tails
msn.Cf_w   = 0.0033;
msn.FF_w   = 1.30;
msn.Cf_t   = 0.0036;
msn.FF_t   = 1.20;
msn.Cf_m   = 0.0040;
msn.FF_m   = 1.30;
msn.Cf_c   = 0.0030;     % configuration-added surfaces
msn.excr   = 1.13;       % excrescence and interference. With no nose
                         %   propeller the forebody sees clean air; 1.06 is
                         %   an ESTIMATE for that, not a sourced number.

%% ===================== PROPULSION ===================================
msn.NPROP   = 8;         % propulsors
% msn.Dprop REMOVED. Propeller diameter is now DERIVED from span packing
% by AEGAprop(), because a fixed value goes stale the moment the wing
% changes: at the converged span of 33 ft the old 2.43 ft understated disc
% area by 46 percent, and blow_wind was deriving a different diameter than
% AEGAsize was using.
msn.use_blown_wind  = true; % 1 if true, 0 if false
msn.fill    = 0.90;      % disc diameter / station pitch
msn.NBLADE  = 5;         % high solidity for blowing, as X-57
msn.AF      = 130;       % blade activity factor. ESTIMATE - needs the
                         %   USAAMRDL TR 73-34B blade data.
msn.kWkg_m  = 7.0;       % motor specific power, project statement.
                         %   Direct drive: 2.43 ft prop at 6000 rpm gives
                         %   helical tip Mach 0.71, so no gearbox needed.
msn.kWkg_pe = 14.0;      % power electronics, project statement
msn.fred    = 0.05;      % redundancy allowance. Was 0.10 for dual windings
                         %   on one shaft; 8 propulsors are redundant by count.
msn.kgkW_th = 0.06;      % thermal management, kg per kW installed. NO SOURCE.
                         %   NASA STARC-ABL basis would give roughly double.
msn.eta_m   = 0.95;
msn.eta_pe  = 0.97;
msn.prof    = 0.86;      % propeller profile factor, CRUISE
msn.etap_cl = 0.65;      % propeller efficiency in CLIMB and TAKEOFF. A prop
                         %   optimised for 120 kt does not hold cruise
                         %   efficiency at 60 kt. Using the cruise value here
                         %   was making AEGAconstraint return 0.085 kW/kg,
                         %   below both the Velis Electro and the 172S.
msn.etap_cr = 0.84;      % propeller efficiency in CRUISE and TURN
msn.PWkWkg  = 0.110;     % takeoff power loading, kW per kg. FROM
                         %   AEGAconstraint with the corrected climb
                         %   efficiency; climb governs. Was hardcoded at
                         %   0.176 inside AEGAsize, which was 60 percent high.
                         %   Re-run AEGAconstraint(msn, out.CD0) after a
                         %   sizing pass and update this by hand; the two are
                         %   not auto-coupled on purpose, to avoid a third
                         %   nested loop.
msn.dWinst  = 120;       % lb, nacelles, pylons, hubs, harness. ALL ESTIMATE:
                         %   64 nacelles + 16 hubs + 40 harness. Now the
                         %   largest unmodelled mass in the aircraft.

%% ===================== BATTERY ======================================
msn.whkg    = 350;       % Wh/kg at PACK level, project statement.
                         %   Velis Electro today: 24.8 kWh / 140 kg = 177.
msn.fusable = 0.90;      % usable fraction of installed capacity

%% ===================== STRUCTURES ===================================
msn.ULF    = 6.0;        % ultimate load factor = 4.0 x 1.5.
                         %   ASTM F2245; Shark 600 Flight Manual confirms
                         %   +4/-2 limit and +6/-3 ultimate.
msn.NSEAT  = 2;
msn.NFLCR  = 1;          % FLOPS Eq. 118 uses 1 for general aviation
msn.Kgear  = 1.0;        % gear length multiplier, 1.0 for a tractor
msn.NEW    = 0;          % KEEP AT 0. FLOPS Eq. 38 inertia relief was
                         %   calibrated on airliner engines; each propulsor
                         %   here is under 10 lb.

%% ===================== SYSTEMS AND CALIBRATION ======================
msn.WAV    = 40;         % lb, avionics. NO SOURCE - itemise from vendor data.
msn.fmarg  = 0.05;       % empty weight margin, conceptual allowance
msn.KELEC  = 0.16;       % on FLOPS Eq. 106, calibrated to Velis Electro
msn.KFURN  = 0.35;       % on FLOPS Eq. 110, same single calibration point
msn.NELEC  = 1;          % propulsor count SEEN BY Eq. 106. The N^0.69 term
                         %   is transport engine-electrical and does not
                         %   apply to distributed electric propulsion:
                         %   it returns 267 lb at N=8 against a bottom-up
                         %   harness estimate near 40 lb. Harness mass is
                         %   carried in dWinst instead.

end